USE UserData;

CREATE TABLE LOGINDATA(
	USERID NVARCHAR(10) NOT NULL UNIQUE,
	PASSWORD NVARCHAR(10) NOT NULL,
	USERNO INT IDENTITY(1,1) NOT NULL,
	QUESTNO TINYINT NOT NULL,
	HINT NVARCHAR(10) NOT NULL,

	PRIMARY KEY(USERID)
);

CREATE TABLE CHARLIST(
	USERNO INT NOT NULL,
	CHARNO INT IDENTITY(1,1) NOT NULL,

	PRIMARY KEY(USERNO, CHARNO)
);

CREATE TABLE CHARINFO(
	CHARNO INT NOT NULL,
	CHARNAME NVARCHAR(10) NOT NULL UNIQUE,
	LV INT NOT NULL,
	EXPERIENCE INT NOT NULL,
	STATPOINT INT NOT NULL,
	HEALTHPOINT INT NOT NULL,
	MANAPOINT INT NOT NULL,
	STRENGTH INT NOT NULL,
	DEXTERITY INT NOT NULL,
	INTELLIGENCE INT NOT NULL,
	MENTALITY INT NOT NULL,
	GOLD INT NOT NULL,
	LASTMAPCODE INT NOT NULL,

	PRIMARY KEY(CHARNO)
);

CREATE TABLE CHAREQUIP(
	CHARNO INT NOT NULL,
	EQUIPNO TINYINT NOT NULL, -- TYPE
	ITEMCODE INT NOT NULL,
	ENHANCE INT NOT NULL,

	PRIMARY KEY(CHARNO, EQUIPNO)
);

CREATE TABLE EQUIPINVEN(
	CHARNO INT NOT NULL,
	INVENNO TINYINT NOT NULL,
	ITEMCODE INT NOT NULL,
	ENHANCE INT NOT NULL,

	PRIMARY KEY(CHARNO, INVENNO)
);

CREATE TABLE EQUIPTYPE(
	ITEMCODE INT NOT NULL,
	EQUIPNO INT NOT NULL, -- TYPE

	PRIMARY KEY(ITEMCODE)
);

CREATE TABLE CHARINVEN(
	CHARNO INT NOT NULL,
	INVENNO TINYINT NOT NULL,
	ITEMCODE INT NOT NULL,
	EXPIRATIONTIME DATETIME NOT NULL,
	ITEMCOUNT INT NOT NULL,

	PRIMARY KEY(CHARNO, INVENNO)
);

CREATE TABLE ITEMTABLE(
	ITEMCODE INT NOT NULL,
	PURCHASEPRICE INT NOT NULL,

	PRIMARY KEY(ITEMCODE)
);